#!/usr/bin/env bash

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

# plugin to use sudo with rbenv, eg for chef
mkdir -p ~/.rbenv/plugins
git clone https://github.com/Davis-A/rbenv-sudo.git ~/.rbenv/plugins/rbenv-sudo

